<?php if (! $compact): ?>
<div class="controls">
    <?= $tabs ?>
</div>
<?php endif ?>
<div class="content">
    <p class="missing-configuration-error"><?= $this->translate('No event types configured yet. You have to configure event types in order to access data in Elasticsearch.') ?></p>
    <div class="actions">
        <?= $this->qlink(
            $this->translate('Create a New Event Type') ,
            'elasticsearch/eventtypes/new',
            null,
            [
                'class'             => 'button-link',
                'data-base-target'  => '_next',
                'icon'              => 'plus',
                'title'             => $this->translate('Create a new event type')
            ]
        ) ?>
    </div>
</div>
