<?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
</div>
<?php endif ?>
<div class="content">

    <?php if ($this->event === null): ?>
        <p><?= $this->translate('Event not found!') ?></p>
    <?php else:
        $document = $this->event->getAll();
    ?>

        <table class="event_detail">
            <?php if ($this->eventType !== null): ?>
            <tr>
                <th><?= $this->translate('Event type') ?></th>
                <td><?= $this->qlink($this->eventType->getLabel(), 'elasticsearch/events', array('type' => $this->eventType->getName())) ?></td>
            </tr>
            <?php endif; ?>
            <tr>
                <th><?= $this->translate('Elasticsearch index') ?></th>
                <td><?= $this->escape($this->event->getIndex()) ?></td>
            </tr>
            <tr>
                <th><?= $this->translate('Elasticsearch type') ?></th>
                <td><?= $this->escape($this->event->getType()) ?></td>
            </tr>
            <tr>
                <th>ID</th>
                <td><?= $this->escape($this->event->getId()) ?></td>
            </tr>
            <tr>
                <th>Timestamp</th>
                <td><?= $this->formatDateTime($timestamp = $this->event->getTimestamp()) ?> (<?= $this->timeAgo($timestamp) ?>)</td>
            </tr>
            <tr>
                <td colspan="2">&nbsp;</td>
            </tr>
            <?php if (($message = $this->event->get('message')) !== null): ?>
                <tr>
                    <th>Message</th>
                    <td class="value"><?= $this->escape($message) ?></td>
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
            <?php endif ?>
            <?php foreach($document as $key => $value):
                if ($key === 'message') continue;
                if ($value === null) continue;
            ?>
            <tr>
                <th><?= $this->escape($key) ?></th>
                <td class="value"><?php
                    if (is_array($value)) {
                        echo '<pre>'.$this->escape(json_encode($value, JSON_PRETTY_PRINT)).'</pre>';
                        //echo $this->escape(implode(', ', $value));
                    }
                    elseif (is_object($value)) {
                        echo '<pre>'.$this->escape(json_encode($value, JSON_PRETTY_PRINT)).'</pre>';
                    }
                    else {
                        echo $this->escape((String) $value);
                    }
                ?></td>
            </tr>
            <?php endforeach ?>
        </table>

        <?php /* TODO: re-implement
        <h4><?= $this->translate('Acknowledge') ?></h4>
        <form method="post" action="<?= $this->url("elasticsearch/event/ack") ?>">
            <label>Action</label>
            <select name="comment_action">
                <option value="ack">Acknowledge</option>
                <option value="unack">Remove acknowledgement</option>
                <option value="comment">Comment only</option>
            </select>
            <br/>
            <label for="comment">Comment</label>
            <textarea name="comment" id="comment" cols="140" rows="4"></textarea><br/>

            <input type="submit" name="acknowledge" value="Save"/>

            <input type="hidden" name="index" value="<?= $this->event->getIndex() ?>"/>
            <input type="hidden" name="type" value="<?= $this->event->getType() ?>"/>
            <input type="hidden" name="id" value="<?= $this->event->getId() ?>"/>

        </form>
        */ ?>

    <?php endif ?>
</div>
