<?php
$severities = array(
    null => '- please choose -',
    1 => 'fatal',
    2 => 'critical',
    3 => 'error',
    4 => 'warning',
    5 => 'notice',
    6 => 'informational',
    7 => 'debug',
);

function programLinks($text, $view) {
    if (preg_match('/^([a-zA-Z0-9]+)/', $text, $m)) {
        $program = $m[1];
        $programLink = $view->qlink($program, $view->url()->with('program', strtolower($program)));
        return preg_replace('/^' . preg_quote($program, '/') . '/', $programLink, $text);
    }
    return $text;
}
?>
<?php if (! $this->compact): ?>
<div class="controls">
<?= $this->tabs ?>
<h3>Syslog<?php if ($this->host) : ?>
: <?= $this->escape($this->host) ?>
<?php endif ?></h3>
</div>
<?php endif ?>
<div class="content">
<?php if (! $this->base_url): ?>
There is no valid config in <?= $this->escape($this->configFile) ?>. You need at least a hostname definition:
<pre>
[elk]
hostname = elk.example.com
</pre>

A full blown configuration could look like this:
<pre>
[elk]
hostname      = elk.example.com
port          = 9200
protocol      = http
index_pattern = "logstash-*"
</pre>
</div>
<?php return; endif ?>
<form action="<?= $this->url()->without('min_severity')->without('program')->without('message') ?>" class="inline" method="post">
Severity: <select name="min_severity" class="autosubmit" style="width: 7em">
<?php foreach ($severities as $sev => $severity): ?>
<option value="<?= $sev ?>"<?= $sev === $this->minSeverity ? ' selected="selected"' : '' ?>><?= $severity ?></option>
<?php endforeach ?>
</select>
Program: <input type="text" name="program" value="<?= $this->escape($this->program) ?>" style="width: 7em" />
Message: <input type="text" name="message" value="<?= $this->escape($this->message) ?>" style="width: 7em" />
<input type="submit" value="Search" style="width: 5em" />
</form>
<?php if ($this->live): ?>
<?= $this->qlink('Refresh slow', $this->url()->without('live')) ?>
<?php else: ?>
<?= $this->qlink('Refreh fast', $this->url()->setParam('live', true)) ?>
<?php endif ?>
<table class="action">
<?php foreach ($this->result->hits->hits as $row): ?>
<tr class="state">
  <td class="state <?= $row->_source->syslog_severity ?>" data-base-target="_next"><a href="<?= $this->url('logstash/show/enry', array(
  '_index' => $row->_index,
  '_id' => $row->_id,

)) ?>"><?= strtoupper(substr($row->_source->syslog_severity, 0, 6)) ?><br /><?= $this->timeSince(strtotime(
  
  isset($row->_source->timestamp) ? $row->_source->timestamp : $row->_source->{'@timestamp'}
   ))  ?></a></td>
   <?php if (! $this->host || $this->compact): ?>
  <td style="width: 10em;">
  <?php if (isset($row->_source->hostname)): ?>
  <?= $this->escape($row->_source->hostname) ?>
  <?php else: ?>
  -
  <?php endif ?>
  </td>
  <?php endif ?>
  <td><?php if (isset($row->_source->program)): ?>
  <?= programLinks($row->_source->program, $this) ?><?php if (isset($row->_source->pid)):
   ?>[<?= $this->escape($row->_source->pid) ?>]<?php endif ?>: 
  <?php endif ?>
  <?php if (is_array($row->_source->message)): ?>
  <?= nl2br($this->escape(implode("\n", $row->_source->message), 1)) ?>
  <?php else: ?>
  <?= $this->escape($row->_source->message) ?>
  <?php endif ?></td>
</tr>
<?php endforeach ?>
</table>
</div>
