<?php /**
 * This table will render events
 *
 * Required view vars:
 *  - $events  array  All events to display in the table
 *  - $fields  array  List of field for columns of the table (if empty it will display JSON)
*/

$events = $this->events;
$fields = $this->fields;
if (!$fields) {
    $fields = array();
}

/**
 * Helper function to display a nice readable column header
 *
 * @param  string  $column
 * @return string
 */
function niceColumn($column) {
    return ucwords(str_replace('_', ' ', strtolower($column)));
}

function getColumnValue($field, &$event, $maxlen=100) {
    if (!array_key_exists($field, $event) || ($value = $event->{$field}) === null) {
        return '';
    }

    if (strlen($value) > $maxlen) {
        return substr($value, 0, $maxlen). ' [...]';
    }
    return $value;
}
?>

<table class="eventTable" data-base-target="_next">
    <?php if (!empty($fields)): ?>
        <thead>
        <tr>
            <th>&nbsp;</th>
            <?php foreach ($fields as $field): ?>
                <th><?= $this->escape(niceColumn($field)) ?></th>
            <?php endforeach; ?>
        </tr>
        </thead>
    <?php endif; ?>

    <tbody>
<?php foreach ($events as $event):
    $classes = array();
    $icons = array();
    /* TODO: re-implement
    if (isset($hit['icinga_status']))
        $classes[] = $hit['icinga_status'] == 2 ? 'critical' :
            ($hit['icinga_status'] == 1 ? 'warning' : '');
    if (isset($hit['icinga_acknowledge']) and $hit['icinga_acknowledge'] === 1) {
        $classes[] = 'handled';
        $icons[] = $this->icon('ok', 'Acknowledged');
    }
    */
    $timestamp = strtotime($event->{'@timestamp'});
    $num = 0;
    $href = $this->url(
        "elasticsearch/event/show",
        array(
            'index' => $event->_index,
            'type' => $event->_type,
            'id' => $event->_id
        )
    );
?>
    <tr class="event state <?= join(' ', $classes) ?>"
        data-elastic-index="<?= $event->_index ?>"
        data-elastic-type="<?= $event->_type ?>"
        data-elastic-id="<?= $event->_id ?>"
        href="<?= $href ?>"
    >
        <td title="<?= $this->formatDateTime($timestamp) ?>"><a href="<?= $href ?>"><?= $this->timeAgo($timestamp) ?></a></td>

        <?php if (count($fields) > 0): ?>
            <?php foreach ($fields as $field): ?>
                <td><?= $this->escape(getColumnValue($field, $event)) ?></td>
            <?php endforeach ?>
        <?php else: ?>
            <td class="rawjson"><pre><?= json_encode($event, JSON_PRETTY_PRINT); ?></pre></td>
        <?php endif ?>
    </tr>
<?php endforeach ?>
    </tbody>
</table>
