<?php if (! $compact): ?>
<div class="controls">
    <?= $tabs ?>
</div>
<?php endif ?>
<div class="content">
    <p class="missing-configuration-error">
        <?= $this->translate('No Elasticsearch instance configured yet. You have to configure an instance before creating event types.') ?>
    </p>
    <div class="actions">
        <?= $this->qlink(
            $this->translate('Create a New Instance') ,
            'elasticsearch/instances/new',
            null,
            [
                'class'             => 'button-link',
                'data-base-target'  => '_self',
                'icon'              => 'plus',
                'title'             => $this->translate('Create a new instance')
            ]
        ) ?>
    </div>
</div>
