    <?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
    <?= $this->limiter; ?>
    <?= $this->paginator; ?>
</div>
<?php endif ?>
<div class="filter">
    <?php if ($this->live): ?>
    <?= $this->qlink('Refresh slow', $this->url()->without('live')) ?>
    <?php else: ?>
    <?= $this->qlink('Refresh fast', $this->url()->setParam('live', true)) ?>
    <?php endif ?>
    -
    <?php if ($this->show_ack): ?>
        <?= $this->qlink('Hide acknowledged', $this->url()->without('show_ack')) ?>
    <?php else: ?>
        <?= $this->qlink('Show Acknowledged', $this->url()->setParam('show_ack', 1)) ?>
    <?php endif ?>
    -
    <?php /* TODO: admin only */ ?>
    <?= $this->qlink('Go to search', $this->url('elasticsearch/event/search', array(
        'query' => $this->query,
        'filter' => $this->filter,
        'fields' => $this->fields,
        'warning' => $this->warning,
        'critical' => $this->critical,
    ))) ?>

</div>
<div class="content">
    <?php /** TODO: split template and load with partial()  */ ?>

    <?php if ($this->count == 0): ?>
        <p>No results found!</p>
    <?php else: ?>

    <p class="small">Found <?= $this->count ?> hits in <?= $this->took ?>ms, <?= $this->warnings ?> warning and <?= $this->criticals ?> critical are shown</p>

    <table class="documents" data-base-target="_next">
    <?php if ($this->count > 0): ?>
        <?php if (count($this->fieldlist) > 0): ?>
        <tr class="header">
            <?php foreach($this->fieldlist as $field): ?>
            <th><?= $this->escape($field) ?></th>
            <?php endforeach ?>
        </tr>
        <?php endif; ?>
        <?php foreach ($this->hits as $hit):
            $classes = array();
            $icons = array();
            if (isset($hit['icinga_status']))
                $classes[] = $hit['icinga_status'] == 2 ? 'critical' :
                    ($hit['icinga_status'] == 1 ? 'warning' : '');
            if (isset($hit['icinga_acknowledge']) and $hit['icinga_acknowledge'] === 1) {
                $classes[] = 'handled';
                $icons[] = $this->icon('ok', 'Acknowledged');
            }
            $num = 0;
            $href = $this->url("elasticsearch/event/show", array('index' => $hit['_index'], 'type' => $hit['_type'], 'id' => $hit['_id']));
        ?>
            <tr class="document state <?= join(" ", $classes) ?>"
                data-elastic-index="<?= $hit['_index'] ?>"
                data-elastic-type="<?= $hit['_type'] ?>"
                data-elastic-id="<?= $hit['_id'] ?>"
                href="<?= $href ?>">
                <?php if(count($this->fieldlist) > 0) foreach($this->fieldlist as $field): ?>
                    <td><?php $value = (array_key_exists($field, $hit) ? $hit[$field] : null);
                        if ($value === null) $value = '&nbsp;';
                        else $value = $this->escape($value);
                        if ($num++ == 0): ?><a href="<?= $href ?>"><?= $value ?></a><?= join("", $icons) ?><?php
                        else: echo $value; endif ?></td>
                <?php endforeach ?>

                <?php if (count($this->fieldlist) == 0): ?>
                    <td class="rawjson"><pre><?= json_encode($hit, JSON_PRETTY_PRINT); ?></pre></td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
        <?php endif ?>
    </table>
    <?php endif ?>
</div>
