<?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
    <?= $this->limiter; ?>
    <?= $this->paginator; ?>
</div>
<?php endif ?>
<div class="filter">
    <form action="<?= $this->url()->without('query')->without('filter')->without('fields') ?>" class="inline" method="get">
        <label for="query">Query:</label><input type="text" name="query" value="<?= $this->escape($this->query) ?>" /><br/>
        <label for="filter">Filter:</label><input type="text" name="filter" value="<?= $this->escape($this->filter) ?>" /><br/>
        <label for="fields">Fields:</label><input type="text" name="fields" value="<?= $this->escape($this->fields) ?>" /><br/>
        <label for="warning">Warning:</label><input type="text" name="warning" value="<?= $this->escape($this->warning) ?>" /><br/>
        <label for="critical">Critical:</label><input type="text" name="critical" value="<?= $this->escape($this->critical) ?>" /><br/>
        <label for="size"></label>
        <input type="submit" value="Search" name="" style="width: 5em" />
    </form>

    <?php if ($this->live): ?>
    <?= $this->qlink('Refresh slow', $this->url()->without('live')) ?>
    <?php else: ?>
    <?= $this->qlink('Refresh fast', $this->url()->setParam('live', true)) ?>
    <?php endif ?>
</div>
<div class="content">

    <?php if ($this->count == 0): ?>
        <p>No results found!</p>
    <?php else: ?>

    <p class="small">Found <?= $this->count ?> hits in <?= $this->took ?>ms</p>

    <table class="documents" data-base-target="_next">
    <?php if ($this->count > 0): ?>
        <?php if (count($this->fieldlist) > 0): ?>
        <tr class="header">
            <?php foreach($this->fieldlist as $field): ?>
            <th><?= $this->escape($field) ?></th>
            <?php endforeach ?>
        </tr>
        <?php endif; ?>
        <?php foreach ($this->hits as $hit):
            $state_class = $hit['icinga_status'] == 2 ? 'critical' :
                ($hit['icinga_status'] == 1 ? 'warning' : '');
            $num = 0;
            $href = $this->url("logstash/event/show", array('index' => $hit['_index'], 'type' => $hit['_type'], 'id' => $hit['_id']));
        ?>
            <tr class="document state <?= $state_class ?>"
                data-elastic-index="<?= $hit['_index'] ?>"
                data-elastic-type="<?= $hit['_type'] ?>"
                data-elastic-id="<?= $hit['_id'] ?>"
                href="<?= $href ?>">
                <?php if(count($this->fieldlist) > 0) foreach($this->fieldlist as $field): ?>
                    <td><?php $value = (array_key_exists($field, $hit) ? $hit[$field] : null);
                        if ($value === null) $value = '&nbsp;';
                        else $value = $this->escape($value);
                        if ($num++ == 0): ?><a href="<?= $href ?>"><?= $value ?></a><?php
                        else: echo $value; endif ?></td>
                <?php endforeach ?>

                <?php if (count($this->fieldlist) == 0): ?>
                    <td class="rawjson"><pre><?= json_encode($hit, JSON_PRETTY_PRINT); ?></pre></td>
                <?php endif ?>
            </tr>
        <?php endforeach ?>
        <?php endif ?>
    </table>
    <?php endif ?>
</div>
